//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 08:59:13 AM UZT 
//


package com.provider.uws;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.provider.uws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.provider.uws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CancelTransactionArguments }
     * 
     */
    public CancelTransactionArguments createCancelTransactionArguments() {
        return new CancelTransactionArguments();
    }

    /**
     * Create an instance of {@link GenericArguments }
     * 
     */
    public GenericArguments createGenericArguments() {
        return new GenericArguments();
    }

    /**
     * Create an instance of {@link GenericParam }
     * 
     */
    public GenericParam createGenericParam() {
        return new GenericParam();
    }

    /**
     * Create an instance of {@link CancelTransactionResult }
     * 
     */
    public CancelTransactionResult createCancelTransactionResult() {
        return new CancelTransactionResult();
    }

    /**
     * Create an instance of {@link GenericResult }
     * 
     */
    public GenericResult createGenericResult() {
        return new GenericResult();
    }

    /**
     * Create an instance of {@link CheckTransactionArguments }
     * 
     */
    public CheckTransactionArguments createCheckTransactionArguments() {
        return new CheckTransactionArguments();
    }

    /**
     * Create an instance of {@link CheckTransactionResult }
     * 
     */
    public CheckTransactionResult createCheckTransactionResult() {
        return new CheckTransactionResult();
    }

    /**
     * Create an instance of {@link GetInformationArguments }
     * 
     */
    public GetInformationArguments createGetInformationArguments() {
        return new GetInformationArguments();
    }

    /**
     * Create an instance of {@link GetInformationResult }
     * 
     */
    public GetInformationResult createGetInformationResult() {
        return new GetInformationResult();
    }

    /**
     * Create an instance of {@link GetStatementArguments }
     * 
     */
    public GetStatementArguments createGetStatementArguments() {
        return new GetStatementArguments();
    }

    /**
     * Create an instance of {@link GetStatementResult }
     * 
     */
    public GetStatementResult createGetStatementResult() {
        return new GetStatementResult();
    }

    /**
     * Create an instance of {@link TransactionStatement }
     * 
     */
    public TransactionStatement createTransactionStatement() {
        return new TransactionStatement();
    }

    /**
     * Create an instance of {@link PerformTransactionArguments }
     * 
     */
    public PerformTransactionArguments createPerformTransactionArguments() {
        return new PerformTransactionArguments();
    }

    /**
     * Create an instance of {@link PerformTransactionResult }
     * 
     */
    public PerformTransactionResult createPerformTransactionResult() {
        return new PerformTransactionResult();
    }

    /**
     * Create an instance of {@link ChangePasswordResult }
     * 
     */
    public ChangePasswordResult createChangePasswordResult() {
        return new ChangePasswordResult();
    }

    /**
     * Create an instance of {@link ChangePasswordArguments }
     * 
     */
    public ChangePasswordArguments createChangePasswordArguments() {
        return new ChangePasswordArguments();
    }

}
