//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 08:59:13 AM UZT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://uws.provider.com/")
package com.provider.uws;
